import Link from "next/link";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireStaff } from "@/lib/require-staff";

const statuses = ["Em análise", "Aguardando peça", "Em reparo", "Pronto para retirada", "Concluído", "Cancelado"];

export default async function Crm() {
  const { supabase } = await requireStaff();
  const { data: appointments } = await supabase.from("appointments").select("*").order("created_at", { ascending: false });
  const { data: pendingReviews } = await supabase.from("customer_reviews").select("*").eq("approved", false).order("created_at", { ascending: false });
  async function updateStatus(data: FormData) { "use server"; const { supabase: client } = await requireStaff(); const status = String(data.get("status")); if (!statuses.includes(status)) return; await client.from("appointments").update({ status }).eq("id", String(data.get("id"))); revalidatePath("/crm"); }
  async function signOut() { "use server"; const client = await createClient(); await client.auth.signOut(); redirect("/"); }
  async function updateReview(data: FormData) { "use server"; const { supabase: client } = await requireStaff(); await client.from("customer_reviews").update({ approved: data.get("approved") === "true" }).eq("id", String(data.get("id"))); revalidatePath("/"); revalidatePath("/crm"); }
  return <main className="crm-page"><header className="crm-header"><Link href="/" className="auth-brand">✚ UTI DO NOTEBOOK</Link><form action={signOut}><button className="btn light">Sair</button></form></header><section className="crm-wrap"><p className="eyebrow teal">Painel interno</p><h1>Agendamentos e ordens</h1><div className="crm-tools"><div><b>Conteúdo do site</b><span>Crie e publique artigos com imagem de capa.</span></div><Link href="/crm/blog" className="btn dark">Gerenciar blog →</Link></div><p className="copy">Total registrado: <b>{appointments?.length ?? 0}</b></p>{appointments?.length ? <div className="table"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Equipamento</th><th>Data</th><th>Defeito</th><th>Status</th></tr></thead><tbody>{appointments.map((appointment) => <tr key={appointment.id}><td><b>{appointment.customer_name}</b></td><td>{appointment.phone}</td><td>{appointment.device_model}</td><td>{new Date(appointment.preferred_date + "T12:00:00").toLocaleDateString("pt-BR")}</td><td>{appointment.issue_description || "—"}</td><td><form action={updateStatus} className="status-form"><input type="hidden" name="id" value={appointment.id}/><select name="status" defaultValue={appointment.status}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button>Salvar</button></form></td></tr>)}</tbody></table></div> : <div className="empty"><b>Nenhum agendamento visível ainda.</b><p>Os pedidos enviados pelo site aparecerão aqui.</p></div>}<section className="reviews-admin"><p className="eyebrow teal">Avaliações do site</p><h2>Comentários aguardando aprovação</h2>{pendingReviews?.length ? <div className="table"><table><thead><tr><th>Cliente</th><th>Nota</th><th>Comentário</th><th>Recebido em</th><th>Ação</th></tr></thead><tbody>{pendingReviews.map((review) => <tr key={review.id}><td><b>{review.customer_name}</b></td><td>{"★".repeat(review.rating)}</td><td>{review.comment}</td><td>{new Date(review.created_at).toLocaleDateString("pt-BR")}</td><td><form action={updateReview} className="status-form"><input type="hidden" name="id" value={review.id}/><button name="approved" value="true">Publicar</button><button name="approved" value="false">Manter pendente</button></form></td></tr>)}</tbody></table></div> : <div className="empty"><b>Nenhuma avaliação aguardando aprovação.</b><p>Os comentários enviados pelo site aparecerão aqui antes de serem publicados.</p></div>}</section></section></main>;
}
