export type Post = { slug: string; title: string; excerpt: string; date: string; image: string; alt: string; body: string[] };

export const posts: Post[] = [
  { slug: "como-limpar-notebook-sem-risco", title: "Como cuidar do notebook no dia a dia sem colocar o equipamento em risco", excerpt: "Pequenos hábitos que ajudam a preservar teclado, tela e desempenho entre uma manutenção e outra.", date: "07 de setembro de 2026", image: "/images/web-blog/limpeza-notebook.jpg", alt: "Limpeza cuidadosa de notebook em bancada técnica", body: ["A limpeza correta começa pelo básico: desligue o equipamento, remova a fonte e use apenas pano de microfibra levemente umedecido na parte externa. Produtos domésticos e excesso de líquido podem comprometer tela e teclado.", "Evite comer ou beber perto do notebook. Poeira, migalhas e umidade chegam aos componentes internos aos poucos e costumam aparecer quando o equipamento já está aquecendo ou apresentando lentidão.", "Quando houver sinais de sujeira interna, ruído de ventoinha ou aquecimento fora do normal, o melhor caminho é uma avaliação técnica. Assim, a limpeza é feita sem improvisos e com atenção aos componentes mais sensíveis."] },
  { slug: "quando-fazer-upgrade-ssd-memoria", title: "SSD e memória: quando um upgrade faz mais sentido que trocar de notebook", excerpt: "Entenda como escolher o investimento que devolve agilidade ao seu equipamento.", date: "04 de setembro de 2026", image: "/images/web-blog/upgrade-ssd-memoria.jpg", alt: "Técnico instalando memória e SSD em notebook", body: ["Muitos notebooks ainda têm boa estrutura, mas ficam lentos por causa de um disco rígido antigo ou pouca memória disponível. Nesses casos, um upgrade bem escolhido pode mudar completamente a experiência de uso.", "O SSD reduz o tempo de inicialização e abre programas com mais rapidez. Já a memória ajuda quando há muitas abas, arquivos e aplicativos em uso ao mesmo tempo.", "Antes de comprar qualquer peça, vale fazer um diagnóstico. Compatibilidade, capacidade e estado geral do notebook definem se o upgrade é a melhor escolha."] },
  { slug: "manutencao-preventiva-notebook", title: "Manutenção preventiva: o cuidado que evita paradas inesperadas", excerpt: "Calor, ruído e lentidão são sinais que merecem atenção antes de virarem um reparo maior.", date: "01 de setembro de 2026", image: "/images/web-blog/manutencao-preventiva.jpg", alt: "Manutenção preventiva no interior de notebook", body: ["A manutenção preventiva cuida do que não aparece por fora: poeira, sistema de ventilação, pasta térmica, conectores e sinais iniciais de desgaste.", "Quando o notebook esquenta mais do que o normal, faz barulho ou reduz o desempenho, não é preciso esperar ele parar. Uma avaliação precoce ajuda a proteger a placa e outros componentes importantes.", "O ideal é definir a frequência de acordo com o uso e o ambiente. Equipamentos de trabalho intenso ou expostos a poeira merecem atenção ainda maior."] },
  { slug: "notebook-lento-o-que-fazer", title: "Notebook lento: por onde começar antes de pensar em trocar de máquina", excerpt: "Lentidão pode ter várias causas — e muitas delas têm solução direta.", date: "28 de agosto de 2026", image: "/images/web-blog/notebook-lento.jpg", alt: "Diagnóstico de desempenho em notebook", body: ["Um notebook lento pode estar com pouco espaço, sistema sobrecarregado, disco desgastado, memória insuficiente ou aquecimento. Por isso, a solução certa começa pela identificação da causa.", "Formatar sem avaliar pode resolver apenas parte do problema. Uma análise técnica considera o histórico do equipamento e evita que uma falha física seja tratada como se fosse apenas software.", "Com o diagnóstico em mãos, fica mais fácil decidir entre limpeza, ajuste de sistema, upgrade ou reparo de componente."] },
  { slug: "como-escolher-notebook", title: "Como escolher um notebook que acompanha a sua rotina", excerpt: "A escolha certa depende mais do seu uso do que de uma especificação isolada.", date: "22 de agosto de 2026", image: "/images/web-blog/escolher-notebook.jpg", alt: "Três notebooks em comparação sobre mesa", body: ["Estudo, trabalho administrativo, edição de imagens ou jogos exigem configurações diferentes. Antes de olhar marca e tamanho, defina quais tarefas o notebook precisa executar todos os dias.", "Processador, memória, armazenamento, tela e bateria formam um conjunto. Um bom equilíbrio evita pagar por recursos que não serão usados — ou comprar uma máquina que logo ficará limitada.", "Na dúvida, converse com uma assistência técnica. Uma recomendação baseada no seu uso costuma ser mais útil do que seguir apenas uma lista genérica de especificações."] },
  { slug: "tela-e-dobradica-cuidados", title: "Tela e dobradiças: sinais de que é hora de avaliar o notebook", excerpt: "Trincas, folgas e falhas na imagem merecem atenção antes que afetem outras peças.", date: "18 de agosto de 2026", image: "/images/web-blog/tela-dobradica.jpg", alt: "Reparo técnico em dobradiça de notebook", body: ["Dobradicas endurecidas, tela com folga ou marcas na carcaça não devem ser ignoradas. O movimento repetido pode puxar cabos e causar danos adicionais ao conjunto da tela.", "Linhas, manchas, piscadas ou imagem que some ao movimentar a tampa também pedem avaliação. Quanto mais cedo o problema é identificado, maior a chance de preservar peças que ainda estão em bom estado.", "O reparo correto considera estrutura, cabos, tela e acabamento. Assim, o notebook volta a abrir e fechar com segurança e a imagem permanece estável."] },
];

export function getPost(slug: string) { return posts.find((post) => post.slug === slug); }
