import Link from "next/link";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireStaff } from "@/lib/require-staff";

function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }

export default async function NewPost() {
  await requireStaff();
  async function createPost(formData: FormData) { "use server"; const { supabase, userId } = await requireStaff(); const title=String(formData.get("title")||"").trim(); const excerpt=String(formData.get("excerpt")||"").trim(); const content=String(formData.get("content")||"").trim(); const slug=slugify(String(formData.get("slug")||title)); const publish=formData.get("publish")==="on"; if (title.length<8 || excerpt.length<30 || content.length<80 || !slug) return; let imageUrl: string | null = null; const image=formData.get("image"); if (image instanceof File && image.size>0) { if (!['image/jpeg','image/png','image/webp'].includes(image.type) || image.size>5242880) return; const extension=image.type.split('/')[1]||'png'; const path=`${userId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError }=await supabase.storage.from("blog-images").upload(path,image,{contentType:image.type,upsert:false}); if (uploadError) return; const { data }=supabase.storage.from("blog-images").getPublicUrl(path); imageUrl=data.publicUrl; } const { error }=await supabase.from("blog_posts").insert({title,slug,excerpt,content,image_url:imageUrl,author_id:userId,published:publish,published_at:publish?new Date().toISOString():null}); if (error) return; revalidatePath("/blog"); revalidatePath(`/blog/${slug}`); redirect("/crm/blog"); }
  return <main className="crm-page"><header className="crm-header"><Link href="/crm/blog" className="auth-brand">← Blog</Link></header><section className="crm-wrap"><p className="eyebrow teal">Novo conteúdo</p><h1>Escrever artigo</h1><form action={createPost} className="editor-form"><label>Título<input name="title" required minLength={8} placeholder="Ex.: O que fazer quando o notebook não liga?"/></label><label>Endereço do artigo <small>Opcional; se deixar vazio, será criado pelo título.</small><input name="slug" placeholder="o-que-fazer-quando-notebook-nao-liga"/></label><label>Resumo<input name="excerpt" required minLength={30} maxLength={320} placeholder="Um resumo curto que aparece no card do blog."/></label><label>Imagem de capa <small>JPG, PNG ou WebP de até 5 MB.</small><input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label>Texto do artigo <small>Separe os parágrafos com uma linha em branco.</small><textarea name="content" required minLength={80} rows={14} placeholder="Escreva o conteúdo aqui..."/></label><label className="publish-check"><input name="publish" type="checkbox"/> Publicar no site agora</label><button className="btn dark" type="submit">Salvar artigo</button></form></section></main>;
}
