import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { SiteChat } from "@/components/site-chat";

const whatsapp = "https://wa.me/5592991388536";

export default async function Home({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) {
  const query = await searchParams;
  async function book(formData: FormData) {
    "use server";
    const data = { customer_name: String(formData.get("name") || "").trim(), phone: String(formData.get("phone") || "").trim(), device_model: String(formData.get("device") || "").trim(), preferred_date: String(formData.get("date") || ""), issue_description: String(formData.get("issue") || "").trim() || null };
    if (!data.customer_name || !data.phone || !data.device_model || !data.preferred_date) redirect("/?error=1#agendamento");
    const supabase = await createClient(); const { error } = await supabase.from("appointments").insert(data);
    redirect(error ? "/?error=1#agendamento" : "/?sent=1#agendamento");
  }
  return <main>
    <div className="utility-bar"><div className="shell"><span>Av. Djalma Batista, 23-A · Chapada, Manaus – AM</span><span>Seg–Sex · 09:00–17:00 · Sáb · 09:00–12:00</span></div></div>
    <header className="site-header"><div className="shell main-nav"><Link href="/" className="brand brand-logo" aria-label="UTI do Notebook - início"><Image src="/images/web-brand/logo-uti-notebook-premium.webp" alt="UTI do Notebook.AM" width={68} height={68} priority/></Link><nav aria-label="Navegação principal"><a href="#servicos">Serviços</a><a href="#sobre">Sobre a empresa</a><a href="#galeria">Galeria</a><a href="#contato">Contacto</a><Link href="/blog">Blog</Link><Link href="/shopping">Shopping</Link></nav><a className="button button-teal" href={whatsapp}>WhatsApp <span aria-hidden>↗</span></a></div></header>
    <section className="hero"><Image src="/images/hero-reparo-premium.jpg" alt="Técnico realizando reparo cuidadoso em notebook" fill priority sizes="100vw" className="hero-image"/><div className="hero-wash"/><div className="shell hero-content"><div className="hero-copy"><p className="kicker">Especialistas em notebooks</p><h1><span className="hero-accent">Solução</span><span className="hero-title-rest">é o que oferecemos</span><br/>aos nossos clientes.</h1><p className="hero-description">Diagnóstico técnico, comunicação clara e reparo especializado para devolver segurança à sua rotina.</p><div className="hero-actions"><a className="button button-orange" href="#agendamento">Agendar avaliação</a><a className="button button-ghost" href={whatsapp}>Pedir orçamento</a></div></div><div className="hero-note"><span>Mais de</span><strong>25</strong><b>anos de experiência técnica</b><i>•</i><span>Atendimento em Manaus</span></div></div></section>
    <section className="booking-panel" id="agendamento"><div className="shell"><form action={book} className="booking-form"><div className="booking-heading"><b>Agende seu atendimento</b><span>Leva menos de um minuto</span></div><label>Nome<input name="name" placeholder="Seu nome" required/></label><label>WhatsApp<input name="phone" placeholder="(92) 9XXXX-XXXX" required/></label><label>Equipamento<input name="device" placeholder="Marca e modelo" required/></label><label>Data<input name="date" type="date" required/></label><label>Defeito<input name="issue" placeholder="O que aconteceu?"/></label><button className="button button-dark" type="submit">Enviar pedido</button></form>{query.sent && <p className="notice">Pedido enviado. Em breve nossa equipe confirma o atendimento.</p>}{query.error && <p className="notice notice-error">Confira os campos obrigatórios e tente novamente.</p>}</div></section>
    <section className="services-section" id="servicos"><div className="shell"><div className="services-intro"><div><p className="kicker">Assistência especializada</p><h2>Diagnóstico investigativo<br/>e assertivo para o seu notebook.</h2></div><p>Identificamos a causa do problema e orientamos a solução adequada — com transparência antes de qualquer reparo.</p></div><div className="service-grid"><Service image="/images/web-blog/manutencao-preventiva.jpg" title="Manutenção e limpeza" text="Prevenção para reduzir aquecimento, lentidão e falhas no dia a dia."/><Service image="/images/web-blog/tela-dobradica.jpg" title="Tela, carcaça e dobradiças" text="Troca e reparo com avaliação da estrutura e da abertura do equipamento."/><Service image="/images/web-blog/upgrade-ssd-memoria.jpg" title="Placa e componentes" text="Diagnóstico de placa-mãe, conectores, teclado, bateria e carregamento."/><Service image="/images/web-blog/notebook-lento.jpg" title="Desempenho e melhorias" text="Mais agilidade para estudar, trabalhar e usar seus programas sem travar."/></div></div></section>
    <section className="shell trust-grid"><Feature number="01" title="Diagnóstico honesto" text="Você entende o problema antes de decidir."/><Feature number="02" title="Técnicos especializados" text="Cuidado técnico para as marcas que você usa."/><Feature number="03" title="Serviço com garantia" text="Mais segurança depois do reparo."/></section>
    <section className="shell about" id="sobre"><div className="about-visual"><Image src="/images/web-space/fachada-uti-notebook.jpg" alt="Fachada da UTI do Notebook na Avenida Djalma Batista" fill sizes="(max-width: 700px) 100vw, 48vw" className="about-image facade-image"/><div className="about-overlay"/><div className="experience-stamp"><strong>25<span>+</span></strong><small>anos de<br/>experiência</small></div><div className="orange-corner"/></div><div className="about-copy"><p className="kicker kicker-dark">Conheça a UTI do Notebook</p><h2>Uma assistência<br/><em>de portas abertas.</em></h2><p>Estamos na Av. Djalma Batista, em frente ao Manaus Plaza Shopping, com uma estrutura preparada para receber você e o seu equipamento com atendimento próximo e criterioso.</p><div className="about-list"><div><span>✓</span><p><b>Especialistas multimarcas</b>Apple, Acer, Lenovo, Samsung, Positivo, Vaio, HP, Dell e mais.</p></div><div><span>✓</span><p><b>Do diagnóstico ao reparo</b>Telas, baterias, teclados, placa, SSD, memória e sistema.</p></div></div><a href="#contato" className="text-link">Ver localização e horários <span>→</span></a></div></section>
    <section className="gallery-section" id="galeria"><div className="shell"><div className="section-heading"><div><p className="kicker kicker-dark">Nosso espaço</p><h2>Chegue, conheça,<br/><em>fique à vontade.</em></h2></div><p>Um atendimento técnico também começa por uma recepção clara, organizada e pronta para ouvir o que o seu equipamento precisa.</p></div><div className="gallery-grid"><figure className="gallery-wide"><Image src="/images/web-space/recepcao-panoramica.jpg" alt="Vista panorâmica da recepção da UTI do Notebook" fill sizes="(max-width: 720px) 100vw, 66vw"/></figure><figure><Image src="/images/web-space/recepcao-entrada.jpg" alt="Entrada e recepção da UTI do Notebook" fill sizes="(max-width: 720px) 100vw, 33vw"/></figure></div></div></section>
    <section className="contact-section" id="contato"><div className="shell contact-grid"><div className="contact-copy"><p className="kicker kicker-dark">Informações de contacto</p><h2>Venha falar<br/><em>com a gente.</em></h2><div className="contact-list"><a href={whatsapp}><b>WhatsApp</b><span>+55 92 99138-8536</span></a><a href="tel:+559230889657"><b>Telefone</b><span>(92) 3088-9657</span></a><a href="https://www.google.com/maps/search/?api=1&query=Av.+Djalma+Batista,+23-A,+Chapada,+Manaus+-+AM" target="_blank" rel="noreferrer"><b>Endereço</b><span>Av. Djalma Batista, 23-A · Chapada<br/>Manaus – AM · 69050-010</span></a></div><div className="hours"><b>Horários de atendimento</b><span>Segunda a sexta · 09:00–17:00</span><span>Sábado · 09:00–12:00</span><span>Domingo · fechado</span></div></div><div className="map-wrap"><iframe title="Mapa da UTI do Notebook" src="https://www.google.com/maps?q=Av.+Djalma+Batista,+23-A,+Chapada,+Manaus+-+AM&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a href="https://www.google.com/maps/search/?api=1&query=Av.+Djalma+Batista,+23-A,+Chapada,+Manaus+-+AM" target="_blank" rel="noreferrer">Abrir rota no Google Maps ↗</a></div></div></section>
    <section className="blog-teaser"><div className="shell"><div><p className="kicker">Informação para decidir melhor</p><h2>Conhecimento<br/>é libertador!</h2></div><p>Ajuda você a decidir se o seu notebook vale a pena ser reparado ou substituído por um novo.</p><Link className="button button-orange" href="/blog">Explorar artigos <span>↗</span></Link></div></section>
    <section className="cta-strip"><div className="shell"><div><p className="kicker kicker-orange">Equipamento com problema?</p><h2>Vamos encontrar a solução.</h2></div><a href={whatsapp} className="button button-orange">Chamar no WhatsApp <span aria-hidden>↗</span></a></div></section><footer className="site-footer"><div className="shell footer-grid"><div><strong>UTI DO NOTEBOOK</strong><p>Assistência técnica especializada em Manaus.</p></div><div><b>Atendimento</b><a href={whatsapp}>WhatsApp: (92) 99138-8536</a><a href="tel:+559230889657">Telefone da loja: (92) 3088-9657</a></div><div><b>Informações</b><a href="#contato">Localização e horários</a><a href="/politica-de-privacidade">Política de privacidade</a><a href="mailto:suporte@utidonotebook.am">Suporte</a></div><form><b>Receba dicas da equipa</b><label><input type="email" placeholder="Seu melhor e-mail" aria-label="Seu melhor e-mail"/><button type="button">Cadastrar</button></label></form></div><div className="shell footer-bottom"><span>© 2026 UTI do Notebook</span><span>Av. Djalma Batista, 23-A · Manaus – AM</span></div></footer>
  <SiteChat /></main>;
}
function Feature({ number, title, text }: { number: string; title: string; text: string }) { return <article className="trust-card"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>; }
function Service({ image, title, text }: { image: string; title: string; text: string }) { return <a className="service-card" href="#agendamento"><Image src={image} alt="" fill sizes="(max-width: 720px) 100vw, 25vw"/><span className="service-card-shade"/><div className="service-card-copy"><h3>{title}</h3><p>{text}</p><span aria-hidden="true">→</span></div></a>; }
