import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

const whatsapp = "https://wa.me/5592991388536";

export default async function Home({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) {
  const query = await searchParams;
  async function book(formData: FormData) {
    "use server";
    const data = { customer_name: String(formData.get("name") || "").trim(), phone: String(formData.get("phone") || "").trim(), device_model: String(formData.get("device") || "").trim(), preferred_date: String(formData.get("date") || ""), issue_description: String(formData.get("issue") || "").trim() || null };
    if (!data.customer_name || !data.phone || !data.device_model || !data.preferred_date) redirect("/?error=1#agendamento");
    const supabase = await createClient(); const { error } = await supabase.from("appointments").insert(data);
    redirect(error ? "/?error=1#agendamento" : "/?sent=1#agendamento");
  }
  return <main>
    <div className="utility-bar"><div className="shell"><span>Av. Djalma Batista, 23-A · Chapada, Manaus – AM</span><span>Seg–Sex · 09:00–18:00 · (92) 3088-9657</span></div></div>
    <header className="site-header"><div className="shell main-nav"><Link href="/" className="brand" aria-label="UTI do Notebook - início"><span className="brand-mark">+</span><span><strong>UTI DO NOTEBOOK</strong><small>Assistência técnica especializada</small></span></Link><nav aria-label="Navegação principal"><a href="#servicos">Serviços</a><a href="#sobre">A assistência</a><a href="#agendamento">Agendar</a><Link href="/login">Área da equipe</Link></nav><a className="button button-teal" href={whatsapp}>WhatsApp <span aria-hidden>↗</span></a></div></header>
    <section className="hero"><Image src="/images/hero-reparo-premium.jpg" alt="Técnico realizando reparo cuidadoso em notebook" fill priority sizes="100vw" className="hero-image"/><div className="hero-wash"/><div className="shell hero-content"><div className="hero-copy"><p className="kicker">Especialistas em notebooks</p><h1>Seu notebook em <em>boas mãos.</em><br/>Do diagnóstico à solução.</h1><p className="hero-description">Assistência técnica com critério, comunicação clara e reparo especializado para você voltar à sua rotina.</p><div className="hero-actions"><a className="button button-orange" href="#agendamento">Agendar avaliação</a><a className="button button-ghost" href={whatsapp}>Pedir orçamento</a></div></div><div className="hero-note"><span>Mais de</span><strong>25</strong><b>anos de experiência técnica</b><i>•</i><span>Atendimento em Manaus</span></div></div></section>
    <section className="booking-panel" id="agendamento"><div className="shell"><form action={book} className="booking-form"><div className="booking-heading"><b>Agende seu atendimento</b><span>Leva menos de um minuto</span></div><label>Nome<input name="name" placeholder="Seu nome" required/></label><label>WhatsApp<input name="phone" placeholder="(92) 9XXXX-XXXX" required/></label><label>Equipamento<input name="device" placeholder="Marca e modelo" required/></label><label>Data<input name="date" type="date" required/></label><label>Defeito<input name="issue" placeholder="O que aconteceu?"/></label><button className="button button-dark" type="submit">Enviar pedido</button></form>{query.sent && <p className="notice">Pedido enviado. Em breve nossa equipe confirma o atendimento.</p>}{query.error && <p className="notice notice-error">Confira os campos obrigatórios e tente novamente.</p>}</div></section>
    <section className="shell trust-grid"><Feature number="01" title="Diagnóstico honesto" text="Você entende o problema antes de decidir."/><Feature number="02" title="Técnicos especializados" text="Cuidado técnico para as marcas que você usa."/><Feature number="03" title="Serviço com garantia" text="Mais segurança depois do reparo."/></section>
    <section className="shell about" id="sobre"><div className="about-visual"><Image src="/images/hero-reparo-premium.jpg" alt="Bancada profissional de reparo de notebooks" fill sizes="(max-width: 700px) 100vw, 48vw" className="about-image"/><div className="about-overlay"/><div className="experience-stamp"><strong>25<span>+</span></strong><small>anos de<br/>experiência</small></div><div className="orange-corner"/></div><div className="about-copy"><p className="kicker kicker-dark">A UTI do Notebook</p><h2>Reparo de qualidade.<br/><em>Conversa direta.</em></h2><p>Notebook parado não pode virar um mistério. Avaliamos o defeito, explicamos as possibilidades e só avançamos com a sua autorização.</p><div className="about-list"><div><span>✓</span><p><b>Orçamento antes de agir</b>Você decide com informação.</p></div><div><span>✓</span><p><b>Atendimento multimarcas</b>Dell, Acer, Lenovo, Apple, Asus, HP e mais.</p></div></div><a href={whatsapp} className="text-link">Falar com um técnico <span>→</span></a></div></section>
    <section className="services-section" id="servicos"><div className="shell"><div className="services-intro"><div><p className="kicker">Nossos serviços</p><h2>O cuidado certo<br/>para cada problema.</h2></div><p>Uma assistência completa para recuperar, proteger e melhorar o desempenho do seu equipamento.</p></div><div className="service-grid"><Service icon="⌁" title="Notebook e desktop" text="Manutenção, limpeza e reparo técnico."/><Service icon="◇" title="Tela e dobradiças" text="Troca de tela, carcaça e estrutura."/><Service icon="◉" title="Placa-mãe" text="Diagnóstico e reparo especializado."/><Service icon="↗" title="Upgrades" text="SSD, memória, sistema e desempenho."/></div></div></section>
    <section className="cta-strip"><div className="shell"><div><p className="kicker kicker-orange">Equipamento com problema?</p><h2>Vamos encontrar a solução.</h2></div><a href={whatsapp} className="button button-orange">Chamar no WhatsApp <span aria-hidden>↗</span></a></div></section><footer><div className="shell"><strong>UTI DO NOTEBOOK</strong><span>Av. Djalma Batista, 23-A · Chapada, Manaus – AM</span><a href={whatsapp}>(92) 3088-9657 · @utidonotebook.am</a></div></footer>
  </main>;
}
function Feature({ number, title, text }: { number: string; title: string; text: string }) { return <article className="trust-card"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>; }
function Service({ icon, title, text }: { icon: string; title: string; text: string }) { return <article className="service-card"><i>{icon}</i><h3>{title}</h3><p>{text}</p><span>→</span></article>; }
