import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireStaff } from "@/lib/require-staff";

function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }

export default async function EditPost({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { supabase } = await requireStaff(); const { data: post } = await supabase.from("blog_posts").select("*").eq("id", id).maybeSingle(); if (!post) notFound();
  async function updatePost(formData: FormData) { "use server"; const { supabase, userId } = await requireStaff(); const title=String(formData.get("title")||"").trim(); const excerpt=String(formData.get("excerpt")||"").trim(); const content=String(formData.get("content")||"").trim(); const slug=slugify(String(formData.get("slug")||title)); const publish=formData.get("publish")==="on"; if (title.length<8 || excerpt.length<30 || content.length<80 || !slug) return; let imageUrl=String(formData.get("existingImage")||"")||null; const image=formData.get("image"); if (image instanceof File && image.size>0) { if (!['image/jpeg','image/png','image/webp'].includes(image.type) || image.size>5242880) return; const extension=image.type.split('/')[1]||'png'; const path=`${userId}/${crypto.randomUUID()}.${extension}`; const { error: uploadError }=await supabase.storage.from("blog-images").upload(path,image,{contentType:image.type,upsert:false}); if (uploadError) return; imageUrl=supabase.storage.from("blog-images").getPublicUrl(path).data.publicUrl; } const { error }=await supabase.from("blog_posts").update({title,slug,excerpt,content,image_url:imageUrl,published:publish,published_at:publish?(post.published_at||new Date().toISOString()):null,updated_at:new Date().toISOString()}).eq("id",id); if (error) return; revalidatePath("/blog"); revalidatePath(`/blog/${slug}`); redirect("/crm/blog"); }
  return <main className="crm-page"><header className="crm-header"><Link href="/crm/blog" className="auth-brand">← Blog</Link></header><section className="crm-wrap"><p className="eyebrow teal">Editar conteúdo</p><h1>Atualizar artigo</h1><form action={updatePost} className="editor-form"><input type="hidden" name="existingImage" value={post.image_url||""}/><label>Título<input name="title" required minLength={8} defaultValue={post.title}/></label><label>Endereço do artigo<input name="slug" defaultValue={post.slug}/></label><label>Resumo<input name="excerpt" required minLength={30} maxLength={320} defaultValue={post.excerpt}/></label><label>Nova imagem de capa <small>Deixe em branco para manter a imagem atual.</small><input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label>Texto do artigo <small>Separe os parágrafos com uma linha em branco.</small><textarea name="content" required minLength={80} rows={14} defaultValue={post.content}/></label><label className="publish-check"><input name="publish" type="checkbox" defaultChecked={post.published}/> Publicar no site</label><button className="btn dark" type="submit">Salvar alterações</button></form></section></main>;
}
